apiVersion: v1
kind: Secret
metadata:
  name: github-app-credentials
type: Opaque
stringData:
  appID: "{{ .Values.github.app.id | toString }}"
  installationID: "{{ .Values.github.app.installationId | toString }}"
  privateKey: |
{{ .Values.github.app.privateKey | indent 4 }}
