apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-github-oauth-external-secret
  namespace: argocd
spec:
  refreshInterval: 24h
  secretStoreRef:
    name: gcp-sm-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name:  argocd-dex-github-client-secret
    creationPolicy: Owner

  data:
    - secretKey: clientSecret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: argocd-oauth-secret
        metadataPolicy: None
