apiVersion: v1
kind: Secret
metadata:
  name: github-app-repo-creds
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: "git"
  url: "https://github.com/{{ .Values.github.org }}"
  githubAppID: "{{ .Values.github.app.id | toString }}"
  githubAppInstallationID: "{{ .Values.github.app.installationId | toString }}"
  githubAppPrivateKey: |
{{ .Values.github.app.privateKey | indent 4 }}
