apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: hello-world-dag
spec:
  entrypoint: hello-dag
  serviceAccountName: argo-workflows
  templates:
    - name: hello-dag
      dag:
        tasks:
          - name: say-hello
            template: hello
          - name: say-world
            template: world
            dependencies: [ say-hello ]

    - name: hello
      container:
        image: alpine:3.18
        command: [ echo ]
        args: [ "Hello" ]

    - name: world
      container:
        image: alpine:3.18
        command: [ echo ]
        args: [ "World!" ]

      container:
        image: bitnami/kubectl:latest
        command: [ "/bin/sh", "-c" ]
        args:
          - |
            echo "Restarting Deployment {{`{{inputs.parameters.deploy-name}}`}} in namespace {{`{{inputs.parameters.deploy-namespace}}`}}"
            kubectl rollout restart deployment/{{`{{inputs.parameters.deploy-name}}`}} -n {{`{{inputs.parameters.deploy-namespace}}`}}
            echo "Deployment {{`{{inputs.parameters.deploy-name}}`}} restarted successfully"
