apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: restart-deployment
spec:
  entrypoint: restart-deployment
  serviceAccountName: argo-workflows

  arguments:
    parameters:
      - name: deployment-name
      - name: deployment-namespace
      - name: timeout
        value: "30m"

  templates:
    - name: restart-deployment
      inputs:
        parameters:
          - name: deployment-name
          - name: deployment-namespace
          - name: timeout
      container:
        image: bitnami/kubectl:latest
        command: [ "/bin/sh", "-c" ]
        # language=bash
        args:
          - |

            echo "Restarting Deployment {{`{{inputs.parameters.deployment-name}}`}} in namespace {{`{{inputs.parameters.deployment-namespace}}`}}"

            kubectl rollout restart deployment/{{`{{inputs.parameters.deployment-name}}`}} \
              -n {{`{{inputs.parameters.deployment-namespace}}`}}

            echo "Waiting for rollout to complete (timeout {{`{{inputs.parameters.timeout}}`}})..."

            kubectl rollout status deployment/{{`{{inputs.parameters.deployment-name}}`}} \
              -n {{`{{inputs.parameters.deployment-namespace}}`}} \
              --timeout={{`{{inputs.parameters.timeout}}`}}

            echo "Deployment {{`{{inputs.parameters.deployment-name}}`}} successfully restarted"
