apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: restart-deployment-v2
spec:
  entrypoint: restart-dag
  serviceAccountName: argo-workflows

  arguments:
    parameters:
      - name: deployment-name
      - name: deployment-namespace

  templates:

    - name: restart-dag
      dag:
        tasks:

          - name: restart
            template: restart-deployment
            arguments:
              parameters:
                - name: deployment-name
                  value: "{{`{{workflow.parameters.deployment-name}}`}}"
                - name: deployment-namespace
                  value: "{{`{{workflow.parameters.deployment-namespace}}`}}"

          - name: get-pods
            dependencies: [ restart ]
            template: list-pods
            arguments:
              parameters:
                - name: deployment-name
                  value: "{{`{{workflow.parameters.deployment-name}}`}}"
                - name: deployment-namespace
                  value: "{{`{{workflow.parameters.deployment-namespace}}`}}"

          - name: wait-each-pod
            dependencies: [ get-pods ]
            template: wait-pod
            arguments:
              parameters:
                - name: deployment-namespace
                  value: "{{`{{workflow.parameters.deployment-namespace}}`}}"
            withParam: "{{`{{tasks.get-pods.outputs.result}}`}}"

    - name: restart-deployment
      inputs:
        parameters:
          - name: deployment-name
          - name: deployment-namespace
      container:
        image: bitnami/kubectl:latest
        command: [ "/bin/sh","-c" ]
        # language=bash
        args:
          - |
            set -eou pipefail
            echo "Restarting deployment {{`{{inputs.parameters.deployment-name}}`}}"
            kubectl rollout restart deployment/{{`{{inputs.parameters.deployment-name}}`}} \
              -n {{`{{inputs.parameters.deployment-namespace}}`}}

    - name: list-pods
      inputs:
        parameters:
          - name: deployment-name
          - name: deployment-namespace
      container:
        image: bitnami/kubectl:latest
        command: [ "/bin/sh","-c" ]
        # language=bash
        args:
          - |
            set -eou pipefail
            kubectl get pods \
              -n {{`{{inputs.parameters.deployment-namespace}}`}} \
              -l app={{`{{inputs.parameters.deployment-name}}`}} \
              -o jsonpath='{.items[*].metadata.name}' | \
              tr ' ' '\n' | jq -R . | jq -s .

    - name: wait-pod
      inputs:
        parameters:
          - name: item
          - name: deployment-namespace
      container:
        image: bitnami/kubectl:latest
        command: [ "/bin/sh","-c" ]
        # language=bash
        args:
          - |
            set -eou pipefail
            POD={{`{{inputs.parameters.item}}`}}
            echo "Waiting for $POD to become Ready..."
            kubectl wait \
              --for=condition=Ready pod/$POD \
              -n {{`{{inputs.parameters.deployment-namespace}}`}} \
              --timeout=5m
