apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: restart-deployment
spec:
  entrypoint: argosay
  arguments:
    - name: deployment-name
    - name: deployment-namespace
  templates:
    - name: restart-deployment
      inputs:
        parameters:
          - name: deployment-name
            value: '{{`workflow.parameters.message`}}'
          - name: deployment-namespace
            value: '{{`workflow.parameters.message`}}'
      container:
        image: bitnami/kubectl:latest
        command: [ "/bin/sh", "-c" ]
        # language=bash
        args:
          - |
            echo "Restarting Deployment {{`{{inputs.parameters.deploy-name}}`}} in namespace {{`{{inputs.parameters.deploy-namespace}}`}}"
            kubectl rollout restart deployment/{{`{{inputs.parameters.deploy-name}}`}} -n {{`{{inputs.parameters.deploy-namespace}}`}}
            echo "Deployment {{`{{inputs.parameters.deploy-name}}`}} restarted successfully"
