argo-cd:
  global:
    domain: argocd.karafra.net
  namespaceOverride: argocd
  configs:
    cm:
      dex.config:
        issuer: https://argocd.karafra.net/api/dex
        connectors:
          - type: github
            id: github
            name: GitHub
            config:
              clientID: $GITHUB_CLIENT_ID
              clientSecret: $GITHUB_CLIENT_SECRET
              orgs:
                - name: KarafrOrg
  server:
    metrics:
      serviceMonitor:
        enabled: true
    replicas: 2
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
    autoscaling:
      enabled: false
    env:
      - name: ARGOCD_API_SERVER_REPLICAS
        value: "2"
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: argocd
            app.kubernetes.io/component: argocd-server
  dex:
    metrics:
      serviceMonitor:
        enabled: true
    resources:
      limits:
        cpu: 50m
        memory: 64Mi
      requests:
        cpu: 10m
        memory: 32Mi
    env:
      - name: GITHUB_CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: argocd-dex-github-client-secret
            key: clientSecret
      - name: GITHUB_CLIENT_ID
        value: your_github_client_id
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: argocd
            app.kubernetes.io/component: argocd-server
  controller:
    replicas: 2
    metrics:
      serviceMonitor:
        enabled: true
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: argocd
            app.kubernetes.io/component: argocd-server
  repoServer:
    metrics:
      serviceMonitor:
        enabled: true
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: argocd
            app.kubernetes.io/component: argocd-server
  applicationSet:
    metrics:
      serviceMonitor:
        enabled: true
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: argocd
            app.kubernetes.io/component: argocd-server
  redis:
    enabled: false
  redis-ha:
    enabled: true
    exporter:
      enabled: true
      resources:
        limits:
          cpu: 50m
          memory: 64Mi
        requests:
          cpu: 10m
          memory: 32Mi
