argo-cd:
  global:
    domain: argocd.karafra.net
    deploymentStrategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 1
        maxSurge: 0
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: argocd
            app.kubernetes.io/component: argocd-server
  namespaceOverride: argocd
  configs:
    params:
      server.insecure: "true"
      admin.enabled: "true"
    rbac:
      policy.default:
        role:readonly
      policy.csv: |
        p, role:admin, applications, *, *, allow
        g, github:KarafrOrg/argocd-admins, role:admin

        p, role:readonly, applications, get, *, allow
        g, github:KarafrOrg/*, role:readonly
  server:
    readinessProbe:
      enabled: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    replicas: 2
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
    autoscaling:
      enabled: false
    env:
      - name: ARGOCD_API_SERVER_REPLICAS
        value: "2"
  controller:
    replicas: 2
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    resources:
      limits:
        cpu: 250m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 256Mi
  repoServer:
    readinessProbe:
      enabled: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  applicationSet:
    readinessProbe:
      enabled: true
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  redis:
    readinessProbe:
      enabled: true
    exporter:
      readinessProbe:
        enabled: true
      enabled: true
      resources:
        limits:
          cpu: 50m
          memory: 64Mi
        requests:
          cpu: 10m
          memory: 32Mi
github:
  org: KarafrOrg
  app:
    id: "2471982"
    installationId: "99589900"
    privateKey: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIEogIBAAKCAQEA9WbepHtxUE/uqu9WLTClFrbRNxrS4zZyEHw2IYA0EFldT9r0
      lIys66zt2Uj/Qx+bhuq5TVwu/bI82WJGNM6FB0Msc0u10/A91vAS2yzrw6ZcwC1D
      SzQkI8Ia2JevXD17LYFNFDdPlTl8+T4lkKkG4UszpTUBuSAbI3F7YK/kdECV8V34
      nFe2zaOzpN4XTRwambZMg5VQj+y7Zby5R5jyRk66jGPyHW4sbdOUlPOgtxR03bbA
      yE711lT315w4llILdQsiI5LxksDSbMZTGdo/XI+TwsklTP1SebL2kiwD33Etddiv
      VhLFi+72ke947MFMalNId1OXV6fOFYyelUyEGwIDAQABAoIBAC9+tWCIM6ojjkGv
      CLK+U3VN9LgBjQdEplbic2eQdIMliJXH/sYxY9ZJJc+D/UN0fpliHHMIgF/Be11n
      U8csoTqCmbvGz24xdQaAeGXLD+ZR8GmRWRDZCpWRH7kDwoDLtWddOxnKirCK69Eh
      YgvZaud3sosq8yZtPFNjx0kzQbft1xIDUD9k9nTSgFXrtbOVpZk/aBiAhLcY3blF
      mchvs1/JCW6zHnTc0RxcvkMn+tpanByMk1wZ48adlbg7x1M02H36z+SYRmICeDHx
      HoPvqhGdlY758G0HE+jvPYyqdd3PDoJxzP2BQPHdQS0dlS9BYxMTgc/VEt5uKL8b
      Ycj2GyECgYEA+sCfwJodF24pzbr0GctmwhWdjl8xn5bZUVWb79cU/SuToERZ9qzs
      8SBbTLdZP3N1ptvnmyloqaSnHhCRsaAhO134vkYg8g1XWDtKbBjhlASgHsUnnjmc
      Bu7a1/L7pMBp0vWCNagPl2sU4KIz/TU88V3KyEUgw853SDe4PpJpeBUCgYEA+omU
      mKupBqxk4m8KIQr3HkAFBGFo/rmralfAK5FsjJE8klWr6BBy5v64FiMRVnrPraaR
      jPGLJ3NyquqdEGMsyEhptDR4ei/mZ8c28sTxmu3ca8apsY+3f18vgHhwBIjuE/4H
      2qcGMtQcyhTk2ifsnSioDIVf5pk8AOA/uuh9Z28CgYB3y7sGuxoW7YyPOzgPcrt/
      EfCZ6iS9B8Z/MxUyumDOqxj2QnFwhiEU+c5kklvTEogs1XaLDHdyRLWKiYPxhn0Z
      7cU+siZfPbxy7LCbgC+VFbihurM4xnEiZs6qyO0sQrjMDnrMw6PfRUtOHnAUEnEx
      JwwQLeZ/ZY5bNDOTwUMeGQKBgA76VqXh7VL2z3kyBjr/etKWJTaj1DEWTIcpA9YW
      9ZRZwnNFJ+fRw+zHYZ4BLrIq2WuaP61ba2RKZJqPOCCYrT60BY2+bU1wu6eMo15U
      I9WNTtYqpE53NxMoT6CwkpHS1djgIPwTbC1xvN7f7OaV6HFk0tccyiTxGEM9JNI5
      v/WFAoGAXtgw5nISLCt7FgNvyDyngw2epcUiHyzo+gcnZtdA3V+LmPloLwjstmEv
      ZBYENQPStpJoqqG4UuniuZlh3BPhLQaVgH+NKfGDHaolJpr3WYn5Xza1ba7aHIYu
      zcvoh5GPMHwm6WEgmFN3hm0fIXIPH+Tvv6Hqf7E3YjYmmit0F+w=
      -----END RSA PRIVATE KEY-----
