apiVersion: argoproj.io/v1alpha1
kind: WorkflowEventBinding
metadata:
  name: delete-resource-event-binding
spec:
  event:
    selector: payload.action == "delete_resource"
  submit:
    workflowTemplateRef:
      name: delete-resource
    arguments:
      parameters:
        - name: resource-name
          valueFrom:
            event: payload.resource_name
        - name: resource-namespace
          valueFrom:
            event: payload.resource_namespace
        - name: resource-kind
          valueFrom:
            event: payload.resource_kind
