apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: delete-workload
spec:
  entrypoint: delete-workload
  serviceAccountName: argo-workflows

  arguments:
    parameters:
      - name: &workloadNameParam workload-name
      - name: &workloadNamespaceParam workload-namespace
      - name: &workloadKindParam workload-kind

  templates:
    - name: delete-workload
      inputs:
        parameters:
          - name: *workloadNameParam
          - name: *workloadNamespaceParam
          - name: *workloadKindParam
      container:
        image: bitnami/kubectl:latest
        # language=bash
        command: [ "/bin/sh", "-c" ]
        # language=bash
        args:
          - |
            set -eou pipefail
            echo "Deleting {{`{{inputs.parameters.workload-kind}}`}} {{`{{inputs.parameters.workload-name}}`}} in namespace {{`{{inputs.parameters.workload-namespace}}`}}"

            kubectl delete {{`{{inputs.parameters.workload-kind}}`}}/{{`{{inputs.parameters.workload-name}}`}} \
              -n {{`{{inputs.parameters.workload-namespace}}`}}
