apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: delete-resource
spec:
  entrypoint: delete-resource
  serviceAccountName: argo-workflows

  arguments:
    parameters:
      - name: &resourceNameParam resource-name
      - name: &resourceNamespaceParam resource-namespace
      - name: &resourceKindParam resource-kind

  templates:
    - name: delete-resource
      inputs:
        parameters:
          - name: *resourceNameParam
          - name: *resourceNamespaceParam
          - name: *resourceKindParam
      container:
        image: bitnami/kubectl:latest
        # language=bash
        command: [ "/bin/sh", "-c" ]
        # language=bash
        args:
          - |
            set -eou pipefail
            echo "Deleting {{`{{inputs.parameters.resource-kind}}`}} {{`{{inputs.parameters.resource-name}}`}} in namespace {{`{{inputs.parameters.resource-namespace}}`}}"

            kubectl delete {{`{{inputs.parameters.resource-kind}}`}}/{{`{{inputs.parameters.resource-name}}`}} \
              -n {{`{{inputs.parameters.resource-namespace}}`}}
